CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260502194226_AddCityTable', '9.0.15');

ALTER TABLE "Cities" ADD "ImageUrl" character varying(500);

CREATE TABLE "Airport" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CityId" integer NOT NULL,
    "IataCode" character varying(3) NOT NULL,
    "ImageUrl" character varying(500),
    CONSTRAINT "PK_Airport" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Airport_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Airport_CityId" ON "Airport" ("CityId");

CREATE UNIQUE INDEX "IX_Airport_IataCode" ON "Airport" ("IataCode");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505171657_CreateTblCityAndAirport', '9.0.15');

ALTER TABLE "Airport" DROP CONSTRAINT "FK_Airport_Cities_CityId";

ALTER TABLE "Airport" DROP CONSTRAINT "PK_Airport";

ALTER TABLE "Airport" RENAME TO "Airports";

ALTER INDEX "IX_Airport_IataCode" RENAME TO "IX_Airports_IataCode";

ALTER INDEX "IX_Airport_CityId" RENAME TO "IX_Airports_CityId";

ALTER TABLE "Cities" ALTER COLUMN "ImageUrl" TYPE character varying(1000);

ALTER TABLE "Airports" ALTER COLUMN "ImageUrl" TYPE character varying(1000);

ALTER TABLE "Airports" ADD CONSTRAINT "PK_Airports" PRIMARY KEY ("Id");

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "PhoneNumber" character varying(11) NOT NULL,
    "Email" character varying(200),
    "PasswordHash" character varying(1000) NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsEmailVerified" boolean NOT NULL,
    "IsPhoneVerified" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LastLoginAt" timestamp with time zone,
    "ImageUrl" character varying(1000),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Admins" (
    "UserId" integer NOT NULL,
    "FirstName" character varying(200) NOT NULL,
    "LastName" character varying(200) NOT NULL,
    "BirthDate" date,
    "Gender" integer NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Admins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Airlines" (
    "UserId" integer NOT NULL,
    "CompanyName" character varying(200) NOT NULL,
    CONSTRAINT "PK_Airlines" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Airlines_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Customers" (
    "UserId" integer NOT NULL,
    "FirstName" character varying(200) NOT NULL,
    "LastName" character varying(200) NOT NULL,
    "BirthDate" date,
    "Gender" integer NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Customers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Flights" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AirlineId" integer NOT NULL,
    "SourceId" integer NOT NULL,
    "DestinationId" integer NOT NULL,
    "Status" integer NOT NULL,
    "FlightNumber" character varying(50) NOT NULL,
    "DepartureTime" timestamp with time zone NOT NULL,
    "ArrivalTime" timestamp with time zone NOT NULL,
    "Capacity" integer NOT NULL,
    "AvailableSeats" integer NOT NULL,
    "Price" numeric(18,3) NOT NULL,
    "Description" character varying(1000),
    CONSTRAINT "PK_Flights" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Flights_Airlines_AirlineId" FOREIGN KEY ("AirlineId") REFERENCES "Airlines" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_Flights_Airports_DestinationId" FOREIGN KEY ("DestinationId") REFERENCES "Airports" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Flights_Airports_SourceId" FOREIGN KEY ("SourceId") REFERENCES "Airports" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Bookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FlightId" integer NOT NULL,
    "BookingDate" timestamp with time zone NOT NULL,
    "PnrCode" character varying(50) NOT NULL,
    "TotalAmount" numeric(18,3) NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Flights_FlightId" FOREIGN KEY ("FlightId") REFERENCES "Flights" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Bookings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Passengers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookingId" integer NOT NULL,
    "FirstName" character varying(200) NOT NULL,
    "LastName" character varying(200) NOT NULL,
    "NationalCode" character varying(10) NOT NULL,
    "BirthDate" date NOT NULL,
    "Gender" integer NOT NULL,
    CONSTRAINT "PK_Passengers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Passengers_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Bookings_FlightId" ON "Bookings" ("FlightId");

CREATE UNIQUE INDEX "IX_Bookings_PnrCode" ON "Bookings" ("PnrCode");

CREATE INDEX "IX_Bookings_UserId" ON "Bookings" ("UserId");

CREATE INDEX "IX_Flights_AirlineId" ON "Flights" ("AirlineId");

CREATE INDEX "IX_Flights_DestinationId" ON "Flights" ("DestinationId");

CREATE UNIQUE INDEX "IX_Flights_FlightNumber" ON "Flights" ("FlightNumber");

CREATE INDEX "IX_Flights_SourceId" ON "Flights" ("SourceId");

CREATE INDEX "IX_Passengers_BookingId" ON "Passengers" ("BookingId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_PhoneNumber" ON "Users" ("PhoneNumber");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

ALTER TABLE "Airports" ADD CONSTRAINT "FK_Airports_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260601140652_AddAllEntitites', '9.0.15');

INSERT INTO "Roles" ("Id", "Name")
VALUES (1, 'Admin');
INSERT INTO "Roles" ("Id", "Name")
VALUES (2, 'Airline');
INSERT INTO "Roles" ("Id", "Name")
VALUES (3, 'Customer');

SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260601143338_SeedData', '9.0.15');

COMMIT;

